name: monthly_update

on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: neo4j
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Run code
        run: python earthquake_main.py
