name: monthly_update

on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update to use Node.js 20
      - name: Setup Python
        uses: actions/setup-python@v4 # Update to use Node.js 20
        with:
          python-version: 3.x
      - name: Run code
        run: python earthquake_main.py
